server:
  port: 18010

logging:
  file: /media/lu/new/log/cuet-data-capture.log
  level: INFO

kafka:
  broker:
    address: 10.0.3.200:9092
  zookeeper:
    connect: 10.0.3.200:2181
  topic: test
  messageKey: key