server:
  port: 18010

logging:
  file: /media/lu/new/log/cuet-data-capture.log
  level: INFO

kafka:
  broker:
    address: 127.0.0.1:9092
  zookeeper:
    connect: 127.0.0.1:2181
  topic: test
  messageKey: key