server:
  port: 18020

logging:
  file: /media/lu/new/log/cuet-data-loader.log
  level: INFO

kafka:
  broker:
    address: 10.0.3.200:9092
  zookeeper:
    connect: 10.0.3.200:2181
  topic: test
  groupId: group-test

spring:
  data:
    elasticsearch:
      properties:
        path:
          home: target/elastic
        transport:
          tcp:
            connect_timeout: 120s

  datasource:
    url: jdbc:postgresql://10.0.3.200:5432/cuet
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    dbcp:
      max-active:
