server:
  port: 18020

logging:
  file: /media/lu/new/log/cuet-data-loader.log
  level: INFO

kafka:
  broker:
    address: 127.0.0.1:9092
  zookeeper:
    connect: 127.0.0.1:2181
  topic: test
  groupId: group-test

spring:
  data:
    elasticsearch:
      cluster-name: mofanghr-search
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true


  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cuet
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver